Fix SpaceEx printer for filenames containing dashes
To reproduce the original bug:

$ for i in cfg xml; do cp ../examples/toy/toy.$i /tmp/foo-bar.$i; done
$ java -jar Hyst.jar -tool spaceex "" -i /tmp/foo-bar.xml -o /tmp/foo-bar-converted.xml
$ spaceex -g /tmp/foo-bar-converted.cfg -m /tmp/foo-bar-converted.xml

ERROR: Failed to define initial states.
caused by: Error parsing location constraint:
loc(foo-bar) == loc1 & x == 5.0 & t == 0.0 & tglobal == 0.0
       ^-bar) == loc1 & x == 5.0 & t == 0.0 & tglobal == 0.0
Internal grammar state:")"